### ISSUE TITLE
Lottie animation library issue or your !!

### ISSUE THREAD

**Issue by GtechGovind** [iamageo/BeautifulDialog#25]
FATAL EXCEPTION: main
                                                                                                    Process: com.atek.atekpos, PID: 3903
                                                                                                    android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class <unknown>
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                                    	at com.iamageo.library.databinding.BeautifulDialogBinding.inflate(BeautifulDialogBinding.java:79)
                                                                                                    	at com.iamageo.library.databinding.BeautifulDialogBinding.inflate(BeautifulDialogBinding.java:73)
                                                                                                    	at com.iamageo.library.BeautifulDialog$Companion.build(BeautifulDialog.kt:41)
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1.invokeSuspend$lambda$0(MainActivity.kt:425)
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1.$r8$lambda$cPPC1fnhMrFeSRIcp9VrX6gOp_M(MainActivity.kt)
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6153)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                                    Caused by: java.lang.IllegalStateException: Unable to parse composition
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.lambda$static$0(LottieAnimationView.java:74)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$$ExternalSyntheticLambda2.onResult(D8$$SyntheticClass)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:86)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:79)
                                                                                                    	at com.airbnb.lottie.LottieTask.addFailureListener(LottieTask.java:109)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.setCompositionTask(LottieAnimationView.java:553)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:437)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.init(LottieAnimationView.java:148)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.<init>(LottieAnimationView.java:123)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                                                    	at com.iamageo.library.databinding.BeautifulDialogBinding.inflate(BeautifulDialogBinding.java:79) 
                                                                                                    	at com.iamageo.library.databinding.BeautifulDialogBinding.inflate(BeautifulDialogBinding.java:73) 
                                                                                                    	at com.iamageo.library.BeautifulDialog$Companion.build(BeautifulDialog.kt:41) 
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1.invokeSuspend$lambda$0(MainActivity.kt:425) 
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1.$r8$lambda$cPPC1fnhMrFeSRIcp9VrX6gOp_M(MainActivity.kt) 
                                                                                                    	at com.atek.atekpos.ui.activity.MainActivity$updateCheckLoop$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                    	at android.os.Looper.loop(Looper.java:154) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6153) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                                    Caused by: java.io.FileNotFoundException: res/raw/success.json
                                                                                                    	at android.content.res.AssetManager.openAsset(Native Method)
                                                                                                    	at android.content.res.AssetManager.open(AssetManager.java:347)
                                                                                                    	at android.content.res.AssetManager.open(AssetManager.java:321)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:220)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.lambda$fromAsset$1(LottieCompositionFactory.java:187)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda10.call(D8$$SyntheticClass)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                    	at java.lang.Thread.run(Thread.java:761)

**Comment by gauravyad69** [comment]
what are you trying to do exactly?

**Comment by iamageo** [comment]
@GtechGovind I'm checking to see if we have any errors, I'll bring updates soon, thank you very much for your issue.

**Comment by iamageo** [comment]
closed due to lack of intervention, I checked the library and did not identify any probable errors, if it persists, please get in touch or provide more details about its implementation.
